CREATE TABLE APL_TB_ARTEFACTA_OTROSCOSTOS (
    GRUPO        VARCHAR2(100)   NOT NULL,
    SUBGRUPO     VARCHAR2(100)   NOT NULL,
    SECUENCIAL   NUMBER(10)      NOT NULL,
    PRECIO       NUMBER(16,2),
    DESCRIPCION  VARCHAR2(500),
    CONSTRAINT PK_APL_TB_ARTEF_OTROSCOSTOS PRIMARY KEY (GRUPO, SUBGRUPO, SECUENCIAL)
)