CREATE TABLE APL_TB_ARTEFACTA_ARTICULOEQUIVALENTE (
    CODIGOARTICULO             VARCHAR2(50) NOT NULL,
    CODIGOARTICULOEQUIVALENTE  VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_APL_TB_ARTEF_ARTEQUIV PRIMARY KEY (CODIGOARTICULO, CODIGOARTICULOEQUIVALENTE)
);