CREATE TABLE APL_TB_ARTEFACTA_GRUPOALMACEN (
    CODIGO          VARCHAR2(50)  NOT NULL,
    NOMBRE          VARCHAR2(200) NOT NULL,
    CODIGOALMACEN   VARCHAR2(50)  NOT NULL,
    CONSTRAINT PK_APL_TB_ARTEF_GRUPOALMACEN PRIMARY KEY (CODIGO),
    CONSTRAINT FK_GRUPOALM_ALMACEN FOREIGN KEY (CODIGOALMACEN)
        REFERENCES APL_TB_ARTEFACTA_ALMACEN(CODIGO)
);