CREATE TABLE APL_TB_ARTEFACTA_ARTICULOPROVEEDOR (
    CODIGO_ARTICULO    VARCHAR2(50)    NOT NULL,
    IDPROVEEDOR        VARCHAR2(50)    NOT NULL,
    ESTADO             VARCHAR2(20),
    CONSTRAINT PK_APL_TB_ART_ARTPROV PRIMARY KEY (CODIGO_ARTICULO, IDPROVEEDOR)
);

--------------------------INSERT
INSERT INTO APL_TB_ARTEFACTA_ARTICULOPROVEEDOR (CODIGO_ARTICULO, IDPROVEEDOR, ESTADO) 
VALUES ('ART-001', 'PROV-001', 'ACTIVO');

INSERT INTO APL_TB_ARTEFACTA_ARTICULOPROVEEDOR (CODIGO_ARTICULO, IDPROVEEDOR, ESTADO) 
VALUES ('ART-002', 'PROV-002', 'INACTIVO');

COMMIT;

