CREATE TABLE APL_TB_ARTEFACTA_ARTICULOPRECIOSCOMPETENCIA (
    CODIGOARTICULO      VARCHAR2(50)    NOT NULL,
    NOMBREEMPRESA       VARCHAR2(200)   NOT NULL,
    VALOR               NUMBER(16,2),
    CONSTRAINT PK_APL_TB_ARTEF_ARTPRECCOMP PRIMARY KEY (CODIGOARTICULO, NOMBREEMPRESA)
);