CREATE TABLE APL_TB_ARTEFACTA_DEPARTAMENTO (
    CODIGO    VARCHAR2(50)    NOT NULL,
    NOMBRE    VARCHAR2(255),
    CONSTRAINT PK_APL_TB_ART_DEPTO PRIMARY KEY (CODIGO)
);

--------
INSERT INTO APL_TB_ARTEFACTA_DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('DEP-001', 'Audio y Video');
INSERT INTO APL_TB_ARTEFACTA_DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('DEP-002', 'Refrigeración');
INSERT INTO APL_TB_ARTEFACTA_DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('DEP-003', 'Computación');
INSERT INTO APL_TB_ARTEFACTA_DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('DEP-004', 'Cocina');
INSERT INTO APL_TB_ARTEFACTA_DEPARTAMENTO (CODIGO, NOMBRE) VALUES ('DEP-005', 'Lavado y Secado');

COMMIT;
