create or replace PROCEDURE APL_SP_BUSCAR_ARTICULO_AUTOCOMPLETE_ITEMS(
    p_texto  IN  VARCHAR2 DEFAULT NULL,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT 
            CODIGO,
            DESCRIPCION
        FROM APL_TB_ARTEFACTA_ARTICULO
        WHERE p_texto IS NULL 
           OR UPPER(CODIGO) LIKE '%' || UPPER(p_texto) || '%'
           OR UPPER(DESCRIPCION) LIKE '%' || UPPER(p_texto) || '%'
        ORDER BY CODIGO
        FETCH FIRST 20 ROWS ONLY;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error en SP_BUSCAR_ARTICULO_AUTOCOMPLETE: ' || SQLERRM);
END APL_SP_BUSCAR_ARTICULO_AUTOCOMPLETE_ITEMS;