CREATE TABLE APL_TB_ARTEFACTA_DIVISION (
    CODIGO    VARCHAR2(50)    NOT NULL,
    NOMBRE    VARCHAR2(255),
    CONSTRAINT PK_APL_TB_ART_DIVISION PRIMARY KEY (CODIGO)
);

------
INSERT INTO APL_TB_ARTEFACTA_DIVISION (CODIGO, NOMBRE) VALUES ('DIV-001', 'Electrónica');
INSERT INTO APL_TB_ARTEFACTA_DIVISION (CODIGO, NOMBRE) VALUES ('DIV-002', 'Línea Blanca');
INSERT INTO APL_TB_ARTEFACTA_DIVISION (CODIGO, NOMBRE) VALUES ('DIV-003', 'Tecnología');
INSERT INTO APL_TB_ARTEFACTA_DIVISION (CODIGO, NOMBRE) VALUES ('DIV-004', 'Hogar');
INSERT INTO APL_TB_ARTEFACTA_DIVISION (CODIGO, NOMBRE) VALUES ('DIV-005', 'Climatización');

COMMIT;

