CREATE TABLE APL_TB_ARTEFACTA_DIVISION (
    CODIGO    VARCHAR2(50)    NOT NULL,
    NOMBRE    VARCHAR2(255),
    CONSTRAINT PK_APL_TB_ART_DIVISION PRIMARY KEY (CODIGO)
);

------
INSERT INTO APL_TB_ARTEFACTA_DIVISION (CODIGO, NOMBRE) VALUES ('DIV-001', 'División Electrónica');
INSERT INTO APL_TB_ARTEFACTA_DIVISION (CODIGO, NOMBRE) VALUES ('DIV-002', 'División Línea Blanca');

COMMIT;