CREATE TABLE Apl_Tb_Artefacta_Marca(
    CODIGO    VARCHAR2(50)    NOT NULL,
    NOMBRE    VARCHAR2(255),
    CONSTRAINT PK_MARCA PRIMARY KEY (CODIGO)
);

----

INSERT INTO APL_TB_ARTEFACTA_MARCA (CODIGO, NOMBRE) VALUES ('MRC-001', 'Samsung');
INSERT INTO APL_TB_ARTEFACTA_MARCA (CODIGO, NOMBRE) VALUES ('MRC-002', 'LG');
INSERT INTO APL_TB_ARTEFACTA_MARCA (CODIGO, NOMBRE) VALUES ('MRC-003', 'Sony');
INSERT INTO APL_TB_ARTEFACTA_MARCA (CODIGO, NOMBRE) VALUES ('MRC-004', 'Whirlpool');
INSERT INTO APL_TB_ARTEFACTA_MARCA (CODIGO, NOMBRE) VALUES ('MRC-005', 'Panasonic');

COMMIT;