CREATE TABLE Apl_Tb_Artefacta_Articulo(
    CODIGO                      VARCHAR2(50)    NOT NULL,
    DESCRIPCION                 VARCHAR2(255),
    COSTO                       NUMBER(16,2),
    STOCK_BODEGA                NUMBER(10),
    STOCK_TIENDAS               NUMBER(10),
    UNIDADES_DISPONIBLES        NUMBER(10),
    INVENTARIO_OPTIMO           NUMBER(10),
    EXCEDENTES_UNIDADES         NUMBER(16,2),
    EXCEDENTES_DOLARES          NUMBER(10),
    M0_UNIDADES                 NUMBER(16,2),
    M0_DOLARES                  NUMBER(10),
    M1_UNIDADES                 NUMBER(16,2),
    M1_DOLARES                  NUMBER(10),
    M2_UNIDADES                 NUMBER(16,2),
    M2_DOLARES                  NUMBER(16,2),
    IGUALAR_PRECIO              NUMBER(10),
    DIAS_ANTIGUEDAD             NUMBER(16,2),
    MARGEN_MIN_CONTADO          NUMBER(16,2),
    MARGEN_MIN_TARJETA_CREDITO  NUMBER(16,2),
    MARGEN_MIN_PRECIO_CREDITO   NUMBER(16,2),
    MARGEN_MIN_IGUALAR          NUMBER(16,2),
    PRECIO_LISTA_CONTADO        NUMBER(16,2),
    PRECIO_LISTA_CREDITO        NUMBER(16,2),
    MARCA                       VARCHAR2(100),
    DIVISION                    VARCHAR2(100),
    DEPARTAMENTO                VARCHAR2(100),
    CLASE                       VARCHAR2(100),
    CONSTRAINT PK_Artefacta_Articulo PRIMARY KEY (CODIGO)
);

---INSERTS

-- Registro 1
INSERT INTO apl_tb_artefacta_articulo (
    CODIGO,
    DESCRIPCION,
    COSTO,
    STOCK_BODEGA,
    STOCK_TIENDAS,
    UNIDADES_DISPONIBLES,
    INVENTARIO_OPTIMO,
    EXCEDENTES_UNIDADES,
    EXCEDENTES_DOLARES,
    M0_UNIDADES,
    M0_DOLARES,
    M1_UNIDADES,
    M1_DOLARES,
    M2_UNIDADES,
    M2_DOLARES,
    IGUALAR_PRECIO,
    DIAS_ANTIGUEDAD,
    MARGEN_MIN_CONTADO,
    MARGEN_MIN_TARJETA_CREDITO,
    MARGEN_MIN_PRECIO_CREDITO,
    MARGEN_MIN_IGUALAR,
    PRECIO_LISTA_CONTADO,
    PRECIO_LISTA_CREDITO,
    MARCA,
    DIVISION,
    DEPARTAMENTO,
    CLASE
) VALUES (
    'PROD-001',
    'Televisor LED 55 pulgadas Smart TV 4K',
    450.75,
    120,
    45,
    165,
    200,
    0.00,
    0,
    25.50,
    12500,
    30.25,
    14800,
    28.00,
    13650.50,
    1,
    45.00,
    15.50,
    12.75,
    18.25,
    10.00,
    599.99,
    649.99,
    'Samsung',
    'Electrónica',
    'Audio y Video',
    'Televisores'
);

-- Registro 2
INSERT INTO apl_tb_artefacta_articulo (
    CODIGO,
    DESCRIPCION,
    COSTO,
    STOCK_BODEGA,
    STOCK_TIENDAS,
    UNIDADES_DISPONIBLES,
    INVENTARIO_OPTIMO,
    EXCEDENTES_UNIDADES,
    EXCEDENTES_DOLARES,
    M0_UNIDADES,
    M0_DOLARES,
    M1_UNIDADES,
    M1_DOLARES,
    M2_UNIDADES,
    M2_DOLARES,
    IGUALAR_PRECIO,
    DIAS_ANTIGUEDAD,
    MARGEN_MIN_CONTADO,
    MARGEN_MIN_TARJETA_CREDITO,
    MARGEN_MIN_PRECIO_CREDITO,
    MARGEN_MIN_IGUALAR,
    PRECIO_LISTA_CONTADO,
    PRECIO_LISTA_CREDITO,
    MARCA,
    DIVISION,
    DEPARTAMENTO,
    CLASE
) VALUES (
    'PROD-002',
    'Refrigeradora No Frost 18 pies cúbicos',
    625.30,
    80,
    25,
    105,
    150,
    10.50,
    6500,
    18.00,
    9800,
    22.75,
    12400,
    15.50,
    8450.25,
    0,
    90.50,
    18.00,
    14.50,
    20.00,
    12.50,
    899.99,
    989.99,
    'LG',
    'Línea Blanca',
    'Refrigeración',
    'Refrigeradoras'
);

-- Confirmar transacción
COMMIT;