CREATE TABLE APL_TB_ARTEFACTA_CLASE (
    CODIGO    VARCHAR2(50)    NOT NULL,
    NOMBRE    VARCHAR2(255),
    CONSTRAINT PK_APL_TB_ART_CLASE PRIMARY KEY (CODIGO)
);
--------
INSERT INTO APL_TB_ARTEFACTA_CLASE (CODIGO, NOMBRE) VALUES ('CLS-001', 'Televisores');
INSERT INTO APL_TB_ARTEFACTA_CLASE (CODIGO, NOMBRE) VALUES ('CLS-002', 'Refrigeradoras');

COMMIT;