CREATE TABLE APL_TB_DESTINATARIOMAIL (
  IDDESTINATARIOMAIL    NUMBER(18,0) 
    GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  ENTIDAD               NUMBER(10)       NOT NULL,
  IDTIPOPROCESO         NUMBER(10)       NOT NULL,
  IDPROVEEDOR           VARCHAR2(15 CHAR),
  PARA                  VARCHAR2(200 CHAR),
  CC                    VARCHAR2(200 CHAR),
  CARGO                 VARCHAR2(30 CHAR),
  IDUSUARIOINGRESO      VARCHAR2(50 CHAR) NOT NULL,
  FECHAINGRESO          TIMESTAMP(6)      DEFAULT SYSTIMESTAMP NOT NULL,
  IDUSUARIOMODIFICA     VARCHAR2(50 CHAR),
  FECHAMODIFICA         TIMESTAMP(6),
  IDESTADOREGISTRO      NUMBER(10),

  CONSTRAINT PK_APL_TB_DESTINATARIOMAIL PRIMARY KEY (IDDESTINATARIOMAIL)
);
