CREATE TABLE APL_TB_FONDOS (
  IDFONDO               NUMBER(18,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
  DESCRIPCION_FONDO     VARCHAR2(100 CHAR),
  IDPROVEEDOR           VARCHAR2(15),
  TIPO_FONDO            NUMBER(18,2),           -- Proveedor/Rebate/Propio
  VALOR_FONDO           NUMBER(18,2),
  FECHA_INICIO_VIGENCIA DATE,
  FECHA_FIN_VIGENCIA    DATE,
  VALOR_DISPONIBLE      NUMBER(18,2),
  VALOR_COMPROMETIDO    NUMBER(18,2),
  VALOR_LIQUIDADO       NUMBER(18,2),
  ESTADO_REGISTRO       NUMBER(18,2),           -- Nuevo/Modificado/Negado/Aprobado/Vigente/Inactivo/Cerrado/Liquidado
  INDICADOR_CREACION    NUMBER(18,2),           -- Manual/Automático
  CONSTRAINT PK_APL_TB_FONDOS PRIMARY KEY (IDFONDO)
);