CREATE TABLE APL_TB_ACUERDOARTICULO (
  IDACUERDOARTICULO    NUMBER(18) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE ORDER) NOT NULL,
  IDACUERDO            NUMBER(18)        NOT NULL,
  CODIGOARTICULO       VARCHAR2(20 CHAR) NOT NULL,
  COSTOACTUAL          NUMBER(18,2)      NOT NULL,
  UNIDADESLIMITE       NUMBER(10)        NOT NULL,
  PRECIOCONTADO        NUMBER(18,2)      NOT NULL,
  PRECIOTARJETACREDITO NUMBER(18,2)      NOT NULL,
  PRECIOCREDITO        NUMBER(18,2)      NOT NULL,
  MARGENCONTADO        NUMBER(18,2)      NOT NULL,
  MARGENTARJETACREDITO NUMBER(18,2)      NOT NULL,
  VALORAPORTE          NUMBER(18,2)      NOT NULL,
  VALORCOMPROMETIDO    NUMBER(18,2)      NOT NULL,
  IDESTADOREGISTRO     NUMBER(10)        NOT NULL,
  CONSTRAINT PK_APL_TB_ACUERDOSITEMS
    PRIMARY KEY (IDACUERDOARTICULO),
  CONSTRAINT FK_APL_TB_ACUERDOSITEMS_APL_TB_ACUERDOS
    FOREIGN KEY (IDACUERDO)
    REFERENCES APL_TB_ACUERDO (IDACUERDO)
);