CREATE TABLE APL_TB_PROMOCIONOTROSCOSTOS (
    IdPromocionOtrosCostos  NUMBER(18,0) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE ORDER) NOT NULL,
    IdPromocionArticulo     NUMBER(18,0) NOT NULL,
    CodigoParametro         NUMBER(10,0) NOT NULL,
    Costo                   NUMBER(18,2) NOT NULL,
    EstadoRegistro          NUMBER(10)   NOT NULL,

    -- Primary Key
    CONSTRAINT PK_APL_TB_PROMOOTROSCOSTOS PRIMARY KEY (IdPromocionOtrosCostos),

    -- Foreign Key
    CONSTRAINT FK_PROMOOTROSCOSTOS_PROMOART FOREIGN KEY (IdPromocionArticulo)
        REFERENCES APL_TB_PROMOCIONARTICULO (IdPromocionArticulo)
);