CREATE TABLE APL_TB_APROBACION (
  IDAPROBACION          NUMBER(18,0) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  ENTIDAD               NUMBER(10)         NOT NULL,
  IDENTIDAD             NUMBER(18,0)       NOT NULL,
  IDTIPOPROCESO         NUMBER(10)         NOT NULL,
  IDUSERSOLICITUD       VARCHAR2(50 CHAR),
  NOMBREUSERSOLICITUD   VARCHAR2(100 CHAR),
  FECHASOLICITUD        TIMESTAMP(6),
  IDUSERAPROBADOR       VARCHAR2(50 CHAR),
  FECHAAPROBACION       TIMESTAMP(6),
  COMENTARIO            VARCHAR2(200 CHAR),
  NIVELAPROBACION       NUMBER(10)         NOT NULL,
  IDESTADOREGISTRO      NUMBER(10),
  NUMEROLOTEAPROBACION	NUMBER (18,0),

  CONSTRAINT PK_APL_TB_APROBACIONES PRIMARY KEY (IDAPROBACION)
);
