CREATE TABLE APL_Tb_ParametroDato (
  IDPARAMETRODATO        NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE ORDER) NOT NULL,
  IDPARAMETRO            NUMBER(10) NOT NULL,
  CODIGOPARAMETRO        NUMBER(10) NOT NULL,
  CODIGORELACION1        VARCHAR2(20),
  CODIGORELACION2        VARCHAR2(20),
  CODIGORELACION3        VARCHAR2(20),
  CODIGORELACION4        VARCHAR2(20),
  CODIGORELACION5        VARCHAR2(20),
  VALOR1                 NUMBER(10,2),
  VALOR2                 NUMBER(10,2),
  VALOR3                 NUMBER(10,2),
  VALOR4                 NUMBER(10,2),
  VALOR5                 NUMBER(10,2),
  IDUSUARIOCREACION      NUMBER(10) NOT NULL,
  FECHACREACION          DATE       NOT NULL,
  IDUSUARIOMODIFICACION  NUMBER(10),
  FECHAMODIFICACION      DATE,
  IDESTADO               NUMBER(10) NOT NULL,
  CONSTRAINT PK_APL_Tb_ParametroDato
    PRIMARY KEY (IDPARAMETRODATO),
  CONSTRAINT FK_APL_TB_PARAMETRO
    FOREIGN KEY (IDPARAMETRO)
    REFERENCES APL_TB_PARAMETRO (IDPARAMETRO)
);