
CREATE TABLE APL_TB_PLANTILLAMAIL (
  IDPLANTILLAMAIL       NUMBER(18,0) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  ENTIDAD               NUMBER(10)       NOT NULL,
  IDTIPOPROCESO         NUMBER(10)       NOT NULL,
  NOMBREARCHIVO         VARCHAR2(50 CHAR),
  IDUSUARIOINGRESO      VARCHAR2(50 CHAR) NOT NULL,
  FECHAINGRESO          TIMESTAMP(6)     DEFAULT SYSTIMESTAMP NOT NULL,
  IDUSUARIOMODIFICA     VARCHAR2(50 CHAR),
  FECHAMODIFICA         TIMESTAMP(6),
  IDESTADOREGISTRO      NUMBER(10),
  
  CONSTRAINT PK_APL_TB_PLANTILLAMAIL PRIMARY KEY (IDPLANTILLAMAIL)
);