CREATE TABLE APL_TB_ACUERDO (
  IDACUERDO            NUMBER(18) GENERATED ALWAYS AS IDENTITY NOT NULL,
  IDTIPOACUERDO        NUMBER(10)        NOT NULL,
  IDMOTIVOACUERDO      NUMBER(10)        NOT NULL,
  DESCRIPCION          VARCHAR2(100 CHAR) NOT NULL,
  FECHAINICIOVIGENCIA  TIMESTAMP(6)      NOT NULL,
  FECHAFINVIGENCIA     TIMESTAMP(6)      NOT NULL,
  FECHAINGRESO         TIMESTAMP(6)      DEFAULT SYSTIMESTAMP NOT NULL,
  IDUSUARIOINGRESO     VARCHAR2(50 CHAR) NOT NULL,
  FECHAMODIFICA        TIMESTAMP(6)      NULL,
  IDUSUARIOMODIFICA    VARCHAR2(50 CHAR) NULL,
  IDESTADOREGISTRO     NUMBER(10)        NOT NULL,
  CONSTRAINT PK_APL_TB_ACUERDOS PRIMARY KEY (IDACUERDO)
);