CREATE TABLE APL_TB_LOTE (
  IDLOTE                NUMBER(18,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
  ENTIDAD               NUMBER(10)         NOT NULL,
  SECUENCIAL            NUMBER(18,0)       NOT NULL,
  
  
  CONSTRAINT PK_APL_TB_LOTE PRIMARY KEY (IDLOTE)
);
