

CREATE TABLE APL_TB_PROMOCIONARTICULOSEGMENTO (
    IdPromocionArticuloSegmento NUMBER(18,0) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE ORDER) NOT NULL,
    IdPromocionArticulo         NUMBER(18,0) NOT NULL,
    IdTipoSegmento              NUMBER(10) NOT NULL,
    TipoAsignacion              CHAR(1) NOT NULL,
    EstadoRegistro              NUMBER(10) NOT NULL,
    
    -- Primary Key
    CONSTRAINT PK_APL_TB_PROMOARTSEGMENTO PRIMARY KEY (IdPromocionArticuloSegmento)
);


ALTER TABLE APL_TB_PROMOCIONARTICULOSEGMENTO 
ADD CONSTRAINT FK_PROMOARTSEG_PROMOART 
FOREIGN KEY (IdPromocionArticulo) 
REFERENCES APL_TB_PROMOCIONARTICULO (IdPromocionArticulo);