CREATE TABLE APL_TB_ACUERDOFONDO (
  IDACUERDOFONDO     NUMBER(18) GENERATED ALWAYS AS IDENTITY NOT NULL,
  IDACUERDO          NUMBER(18)        NOT NULL,
  IDFONDO            NUMBER(18)        NOT NULL,
  VALORAPORTE        NUMBER(18,2)      NOT NULL,
  VALORDISPONIBLE    NUMBER(18,2)      NOT NULL,
  VALORCOMPROMETIDO  NUMBER(18,2)      NOT NULL,
  VALORLIQUIDADO     NUMBER(18,2)      NOT NULL,
  IDESTADOREGISTRO   NUMBER(10)        NOT NULL,

  CONSTRAINT PK_APL_TB_ACUERDOSFONDOS
    PRIMARY KEY (IDACUERDOFONDO),

  CONSTRAINT FK_APL_TB_ACUERDOSFONDOS_ACUERDOS
    FOREIGN KEY (IDACUERDO)
    REFERENCES APL_TB_ACUERDO (IDACUERDO),

  CONSTRAINT FK_APL_TB_ACUERDOSFONDOS_FONDOS
    FOREIGN KEY (IDFONDO)
    REFERENCES APL_TB_FONDO (IDFONDO)
);