CREATE TABLE APL_Tb_CatalogoTipo(
  IDCATALOGOTIPO               NUMBER(10) GENERATED ALWAYS AS IDENTITY
                               -- Si prefieres editable por app: GENERATED BY DEFAULT AS IDENTITY
                               -- Opcionalmente: (START WITH 1 INCREMENT BY 1 NOCACHE),
                               NOT NULL,
  NOMBRE                       VARCHAR2(100 CHAR)     NOT NULL,
  DESCRIPCION                  VARCHAR2(350 CHAR)     NULL,
  IDUSUARIOCREACION            NUMBER(10)             NOT NULL,
  FECHACREACION                DATE                   NOT NULL,  -- DATE en Oracle ya incluye fecha y hora
  IDUSUARIOMODIFICACION        NUMBER(10)             NULL,
  FECHAMODIFICACION            DATE                   NULL,
  IDESTADO                     NUMBER(10)             NOT NULL,
  IDMARCAABREVIATURAAUTOMATICA NUMBER(10)             NULL,
  IDETIQUETA                   VARCHAR2(30 CHAR)      NULL,
  CONSTRAINT PK_APL_TB_CATALOGOTIPO
    PRIMARY KEY (IDCATALOGOTIPO)
);

====================INSERT=======================
INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Estado', 'Estado de Regístros', 1, SYSDATE, NULL, TO_DATE('2022-09-06 13:35:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 'ESTADOS');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Grupo', 'Grupo de Opciones de Navegacion', 1, SYSDATE, NULL, TO_DATE('2022-09-06 13:35:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 'GRUPOOPCION');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Tipo de Servicio', 'Tipo de Servicios o Modulos', 1, SYSDATE, NULL, TO_DATE('2022-09-06 13:35:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 'TIPOSERVICIO');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Pais', 'Paises', 1, SYSDATE, NULL, TO_DATE('2024-10-06 13:35:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 'PAISES');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Moneda', 'Moneda', 1, SYSDATE, NULL, TO_DATE('2024-10-06 13:35:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 'MONEDAS');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Tipo de Autenticación', 'Tipo de Autenticación', 1, SYSDATE, NULL, TO_DATE('2024-10-06 13:35:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 'TIPOAUTENTICACION');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Controles de Interfaz', 'Controles de Interfaz de Usuario', 1, SYSDATE, NULL, TO_DATE('2024-10-06 13:35:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 'CONTROLUI');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Tipo de Eventos', 'Tipo de Eventos', 1, SYSDATE, NULL, TO_DATE('2024-10-06 13:35:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 'EVENTOS');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Entidad', 'Entidad que identifica la informacion', 1, SYSDATE, NULL, TO_DATE('2024-10-06 13:35:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 'ENTIDAD');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Tipo de Fondo', 'Tipo de Fondo', 1, SYSDATE, NULL, TO_DATE('2024-10-06 13:35:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 'TIPOFONDO');


 INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Indicador de Creacion', 'Indicador de Creacion', 1, SYSDATE, NULL, TO_DATE('2024-10-06 13:35:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 'INCRE');
 
  INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Tipo de Proceso', 'Tipo de Proceso', 1,  SYSDATE, NULL, TO_DATE('2024-10-06 13:35:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 'TIPOPROCESO');

--acuedos 12/11/2025
  INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Tipo de Acuerdo', 'Tipo de Acuerdo', 1,  SYSDATE, NULL, TO_DATE('2024-10-06 13:35:05', 'YYYY-MM-DD HH24:MI:SS'), 1, 0, 'TIPOACUERDO');