CREATE TABLE APL_TB_LOG (
  IDLOG              NUMBER(18,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
  FECHAHORATRX       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  IDUSER             VARCHAR2(50 CHAR) NOT NULL,
  IDOPCION           NUMBER(10) NOT NULL,
  IDCONTROLINTERFAZ  NUMBER(10) NOT NULL,
  IDEVENTO           NUMBER(10) NOT NULL,
  ENTIDAD            NUMBER(10) NOT NULL,
  IDENTIDAD          NUMBER(18,0) NOT NULL,
  IDTIPOPROCESO      NUMBER(10) NOT NULL,
  DATOS              JSON NOT NULL,
  CONSTRAINT PK_APL_TB_LOGS PRIMARY KEY (IDLOG)
);