CREATE TABLE APL_TB_CATALOGO (
  IDCATALOGO            NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
  NOMBRE                VARCHAR2(150 CHAR)  NOT NULL,
  ADICIONAL             VARCHAR2(300 CHAR),
  ABREVIATURA           CHAR(10 CHAR),
  IDCATALOGOTIPO        NUMBER(10)          NOT NULL,
  IDUSUARIOCREACION     NUMBER(10)          NOT NULL,
  FECHACREACION         DATE                NOT NULL,
  IDUSUARIOMODIFICACION NUMBER(10),
  FECHAMODIFICACION     DATE,
  IDESTADO              NUMBER(10)          NOT NULL,
  IDETIQUETA            VARCHAR2(30 CHAR),
  CONSTRAINT PK_APL_TB_CATALOGO
    PRIMARY KEY (IDCATALOGO),
  CONSTRAINT FK_APL_TB_CATALOGOTIPO
    FOREIGN KEY (IDCATALOGOTIPO)
    REFERENCES APL_TB_CATALOGOTIPO (IDCATALOGOTIPO)
);

=======================INSERT===============================
-- 1
INSERT INTO APL_TB_CATALOGO (
  NOMBRE, ADICIONAL, ABREVIATURA,
  IDCATALOGOTIPO,
  IDUSUARIOCREACION, FECHACREACION,
  IDUSUARIOMODIFICACION, FECHAMODIFICACION,
  IDESTADO, IDETIQUETA
)
VALUES (
  'CATÁLOGO GENERAL',
  'Valores por defecto del sistema',
  'GEN',
  1,
  1, SYSDATE,
  NULL, NULL,
  1, 'GEN'
);

-- 2
INSERT INTO APL_TB_CATALOGO (
  NOMBRE, ADICIONAL, ABREVIATURA,
  IDCATALOGOTIPO,
  IDUSUARIOCREACION, FECHACREACION,
  IDUSUARIOMODIFICACION, FECHAMODIFICACION,
  IDESTADO, IDETIQUETA
)
VALUES (
  'CATÁLOGO ESPECIAL',
  'Configuración extendida para casos específicos',
  'ESP',
  2,
  2, SYSDATE,
  NULL, NULL,
  1, 'ESP'
);

-- 3
INSERT INTO APL_TB_CATALOGO (
  NOMBRE, ADICIONAL, ABREVIATURA,
  IDCATALOGOTIPO,
  IDUSUARIOCREACION, FECHACREACION,
  IDUSUARIOMODIFICACION, FECHAMODIFICACION,
  IDESTADO, IDETIQUETA
)
VALUES (
  'CATÁLOGO INTERNO',
  'Uso interno del sistema',
  'INT',
  3,
  3, SYSDATE,
  NULL, NULL,
  0, 'INT'
);


