  CREATE TABLE "APPAPL"."APL_TB_LIQUIDACIONPROMOCION" 
   (	"IDLIQUIDACIONPROMOCION" NUMBER(18,0), 
	"IDPROMOCION" NUMBER(18,0) NOT NULL ENABLE, 
	"IDUSUARIOINGRESO" VARCHAR2(50 CHAR), 
	"FECHAINGRESO" TIMESTAMP (6), 
	"IDUSUARIOMODIFICA" VARCHAR2(50 CHAR), 
	"FECHAMODIFICA" TIMESTAMP (6), 
	"IDESTADOREGISTRO" NUMBER(10,0), 
	 PRIMARY KEY ("IDLIQUIDACIONPROMOCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "APPAPL_DATA"  ENABLE, 
	 CONSTRAINT "FK_APL_LIQ_PROMO" FOREIGN KEY ("IDPROMOCION")
	  REFERENCES "APPAPL"."APL_TB_PROMOCION" ("IDPROMOCION") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APPAPL_DATA" ;

  CREATE INDEX "APPAPL"."IDX_APL_LIQ_PROMO_IDPROMO" ON "APPAPL"."APL_TB_LIQUIDACIONPROMOCION" ("IDPROMOCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPAPL_DATA" ;