
  CREATE TABLE "APPAPL"."APL_TB_LIQUIDACIONPROMOCIONNOTADEBITO" 
   (	"IDLIQUIDACIONPROMOCION" NUMBER(18,0) NOT NULL ENABLE, 
	"IDPROVEEDOR" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	"VALORDEBITO" NUMBER(18,2) NOT NULL ENABLE, 
	"IDESTADOREGISTRO" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "FK_LIQ_PROMO_NOTADEBITO" FOREIGN KEY ("IDLIQUIDACIONPROMOCION")
	  REFERENCES "APPAPL"."APL_TB_LIQUIDACIONPROMOCION" ("IDLIQUIDACIONPROMOCION") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APPAPL_DATA" ;

  CREATE INDEX "APPAPL"."IDX_LIQ_PROMO_NOTADEBITO" ON "APPAPL"."APL_TB_LIQUIDACIONPROMOCIONNOTADEBITO" ("IDLIQUIDACIONPROMOCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPAPL_DATA" ;

