CREATE TABLE APL_Tb_Parametro (
  IDPARAMETRO            NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE ORDER) NOT NULL,
  IDPARAMETROTIPO        NUMBER(10) NOT NULL,
  NOMBRE                 VARCHAR2(150 CHAR)  NOT NULL,
  CODIGOPARAMETRO        NUMBER(10) NOT NULL,
  IDUSUARIOCREACION      NUMBER(10) NOT NULL,
  FECHACREACION          DATE       NOT NULL,
  IDUSUARIOMODIFICACION  NUMBER(10),
  FECHAMODIFICACION      DATE,
  IDESTADO               NUMBER(10) NOT NULL,
  CONSTRAINT PK_APL_TB_PARAMETRO
    PRIMARY KEY (IDPARAMETRO),
  CONSTRAINT FK_APL_TB_PARAMETROTIPO
    FOREIGN KEY (IDPARAMETROTIPO)
    REFERENCES APL_TB_PARAMETROTIPO (IDPARAMETROTIPO)
);

