CREATE TABLE APL_Tb_CatalogoTipo(
  IDCATALOGOTIPO               NUMBER(10) GENERATED ALWAYS AS IDENTITY
                               -- Si prefieres editable por app: GENERATED BY DEFAULT AS IDENTITY
                               -- Opcionalmente: (START WITH 1 INCREMENT BY 1 NOCACHE),
                               NOT NULL,
  NOMBRE                       VARCHAR2(100 CHAR)     NOT NULL,
  DESCRIPCION                  VARCHAR2(350 CHAR)     NULL,
  IDUSUARIOCREACION            NUMBER(10)             NOT NULL,
  FECHACREACION                DATE                   NOT NULL,  -- DATE en Oracle ya incluye fecha y hora
  IDUSUARIOMODIFICACION        NUMBER(10)             NULL,
  FECHAMODIFICACION            DATE                   NULL,
  IDESTADO                     NUMBER(10)             NOT NULL,
  IDMARCAABREVIATURAAUTOMATICA NUMBER(10)             NULL,
  IDETIQUETA                   VARCHAR2(30 CHAR)      NULL,
  CONSTRAINT PK_APL_TB_CATALOGOTIPO
    PRIMARY KEY (IDCATALOGOTIPO)
);

====================INSERT=======================
INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('TipoPersona', 'Define si es Natural o Persona Juridica', 1, TO_DATE('2022-08-08 10:51:49', 'YYYY-MM-DD HH24:MI:SS'), 1, TO_DATE('2022-09-06 13:35:05', 'YYYY-MM-DD HH24:MI:SS'), 12, 15, 'TIPOPERSONA');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('TipoIdentificacion', 'Tipo de Identificacion C/R/P', 1, TO_DATE('2022-08-08 10:51:49', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, 12, 15, 'TIPOIDENTIFICACION');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Sexo', 'Define Hombre o Mujer', 1, TO_DATE('2022-08-08 10:51:49', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, 12, 15, 'SEXO');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('TituloProfesional', 'Titulo de Tercer Nivel', 1, TO_DATE('2022-08-08 10:51:49', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, 12, 15, 'TITULOPROFESIONAL');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('TituloPostGrado', 'Titulo de Cuarto Nivel', 1, TO_DATE('2022-08-08 10:51:49', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, 12, 15, 'TITULOPOSTGRADO');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Estado', 'Estado de Registros', 1, TO_DATE('2022-08-08 10:51:49', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, 12, 15, 'ESTADOS');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Varios', 'Manejo de controles o Secuencias', 1, TO_DATE('2022-08-08 10:51:49', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, 12, 15, 'VARIOS');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('TipoDireccion', 'Direccion Principal/Oficina/etc', 1, TO_DATE('2022-08-08 10:51:49', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, 12, 15, 'TIPODIRECCION');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Grupo', 'Grupo de Opciones de Navegacion', 1, TO_DATE('2022-08-08 10:51:49', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, 12, 15, 'GRUPOOPCION');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('PerfilUsuario', 'Perfile de Usuario (Permisos)', 1, TO_DATE('2022-08-08 10:51:49', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, 12, 15, 'PERFILUSUARIO');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('TipoCliente', 'Tipo de Cliente', 1, TO_DATE('2022-08-08 10:51:49', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, 12, 15, 'TIPOCLIENTE');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('TipoFuncionario', 'Tipo de Funcionario', 1, TO_DATE('2022-08-09 15:50:04', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, 12, 15, 'TIPOFUNCIONARIO');

INSERT INTO APL_TB_CATALOGOTIPO (Nombre, Descripcion, IdUsuarioCreacion, FechaCreacion, IdUsuarioModificacion, FechaModificacion, IdEstado, IdMarcaAbreviaturaAutomatica, IdEtiqueta) 
VALUES ('Tipo de Empresa', 'Define el tipo de empresa', 1, TO_DATE('2022-10-21 15:09:04', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, 12, 15, 'TIPOEMPRESA');
 
 
 