
CREATE TABLE APL_TB_APROBADOR (
  IDAPROBADOR          NUMBER(18,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
  ENTIDAD              NUMBER(10) NOT NULL,
  IDTIPOPROCESO        NUMBER(10) NOT NULL,
  IDUSERAPROBADOR      VARCHAR2(50 CHAR),
  NIVELAPROBACION      NUMBER(10) NOT NULL,
  IDUSUARIOINGRESO     VARCHAR2(50 CHAR) NOT NULL,
  FECHAINGRESO         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  IDUSUARIOMODIFICA    VARCHAR2(50 CHAR),
  FECHAMODIFICA        TIMESTAMP(6),
  IDESTADOREGISTRO     NUMBER(10),
  
  CONSTRAINT PK_APL_TB_APROBADOR PRIMARY KEY (IDAPROBADOR)
);