CREATE TABLE APL_Tb_ParametroTipo(
  IDPARAMETROTIPO               NUMBER(10) GENERATED ALWAYS AS IDENTITY
                               -- Si prefieres editable por app: GENERATED BY DEFAULT AS IDENTITY
                               -- Opcionalmente: (START WITH 1 INCREMENT BY 1 NOCACHE),
                               NOT NULL,
  NOMBRE                       VARCHAR2(100 CHAR)     NOT NULL,
  DESCRIPCION                  VARCHAR2(350 CHAR)     NULL,
  IDUSUARIOCREACION            NUMBER(10)             NOT NULL,
  FECHACREACION                DATE                   NOT NULL,  -- DATE en Oracle ya incluye fecha y hora
  IDUSUARIOMODIFICACION        NUMBER(10)             NULL,
  FECHAMODIFICACION            DATE                   NULL,
  IDESTADO                     NUMBER(10)             NOT NULL,
  IDMARCAABREVIATURAAUTOMATICA NUMBER(10)             NULL,
  IDETIQUETA                   VARCHAR2(30 CHAR)      NULL,
  CONSTRAINT PK_APL_TB_PARAMETROTIPO
    PRIMARY KEY (IDPARAMETROTIPO)
);

--TIPO PARAMTERO
INSERT INTO apl_tb_parametrotipo (nombre, descripcion, idusuariocreacion, fechacreacion, idusuariomodificacion, fechamodificacion, idestado, idmarcaabreviaturaautomatica,idetiqueta) 
	VALUES ('Motivo Creacion Acuerdo', 'Motivo Creacion Acuerdo', 1, SYSDATE, NULL, NULL, 1, 0, 'MOTIVOAC');