
CREATE TABLE APL_TB_PROMOCIONARTICULOACUERDO (
    IdPromocionArticuloAcuerdo  NUMBER(18,0) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE ORDER) NOT NULL,
    IdPromocionArticulo         NUMBER(18,0) NOT NULL,
    IdAcuerdo                   NUMBER(18,0) NOT NULL,
    ValorAporte                 NUMBER(18,2) NOT NULL,
    ValorComprometido           NUMBER(18,2) NOT NULL,
    ValorLiquidado              NUMBER(18,2) NOT NULL,
    EstadoRegistro              NUMBER(10) NOT NULL,
    
    -- Primary Key
    CONSTRAINT PK_APL_TB_PROMOARTACUERDO PRIMARY KEY (IdPromocionArticuloAcuerdo)
);


ALTER TABLE APL_TB_PROMOCIONARTICULOACUERDO 
ADD CONSTRAINT FK_PROMOARTACUERDO_ACUERDO 
FOREIGN KEY (IdAcuerdo) 
REFERENCES APL_TB_ACUERDO (IdAcuerdo);

ALTER TABLE APL_TB_PROMOCIONARTICULOACUERDO 
ADD CONSTRAINT FK_PROMOARTACUERDO_PROMOART 
FOREIGN KEY (IdPromocionArticulo) 
REFERENCES APL_TB_PROMOCIONARTICULO (IdPromocionArticulo);